[package]
name = "pkgutils"
version = "0.1.0"

[lib]
name = "pkgutils"
path = "src/lib.rs"

[[bin]]
name = "pkg"
path = "src/bin/pkg.rs"

[dependencies]
termion = "1.1"

[dependencies.octavo]
version = "0.1"
default-features = false
features = ["digest"]
