[package]
name = "pkgutils"
version = "0.1.0"

[lib]
name = "pkgutils"
path = "src/lib.rs"

[[bin]]
name = "pkg"
path = "src/bin/pkg.rs"

[dependencies]
termion = "1.1"
hyper-rustls = "0.3"
tar = { git = "https://github.com/redox-os/tar-rs" }

[dependencies.hyper]
version = "0.10"
default-features = false

[dependencies.octavo]
git = "https://github.com/libOctavo/octavo.git"
default-features = false
features = ["digest"]
