[package]
name = "pkgutils"
version = "0.1.0"

[lib]
name = "pkgutils"
path = "src/lib.rs"

[[bin]]
name = "pkg"
path = "src/bin/pkg.rs"

[dependencies]
liner = "0.1"
hyper-rustls = "0.6"
serde = "1.0"
serde_derive = "1.0"
tar = { git = "https://github.com/redox-os/tar-rs" }
toml = "0.4"
version-compare = "0.0.4"
pbr = { version = "1.0", git = "https://github.com/ids1024/pb", branch = "redox" }

[dependencies.hyper]
version = "0.10"
default-features = false

[dependencies.octavo]
git = "https://github.com/libOctavo/octavo.git"
default-features = false
features = ["digest"]
