[package]
name = "pkgutils"
version = "0.1.0"

[[bin]]
name = "pkg"
path = "src/pkg/main.rs"

[dependencies]
termion = "*"

[dependencies.octavo]
git = "https://github.com/libOctavo/octavo"
default-features = false
features = ["digest"]

[replace]
"libc:0.2.17" = { git = "https://github.com/redox-os/liblibc.git", branch = "redox" }
"rustc-serialize:0.3.19" = { git = "https://github.com/redox-os/rustc-serialize.git" }
